version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: sa_nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

  redis:
    image: redis:rc-alpine
    container_name: sa_redis
    ports:
        - 6379:6379
    networks:
      - redis_nt

networks:
  nginx_network:
    driver: bridge
  redis_nt:
    driver: bridge

