FROM python:3.6-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV FLASK_APP=cervix/run_web_server.py
ENV FLASK_RUN_HOST=0.0.0.0
# RUN apk add --no-cache gcc cmake make automake g++ python3-dev musl-dev linux-headers
# RUN apk add --no-cache build-base gcc cmake make automake g++ python3-dev musl-dev linux-headers
RUN apk update \
    && apk --no-cache --update add build-base cmake automake \
    gfortran openblas-dev lapack-dev cython \
    python3-dev \
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]
