version: "3"

services:
  web:
    image: titedios/sa_web
    container_name: sa_web
    ports:
      - 5001:5001
    networks:
      - nginx_network
      - redis_nt

  model:
    image: titedios/sa_model
    container_name: sa_model
    networks:
      - redis_nt

  nginx:
    image: nginx:stable-alpine
    container_name: sa_nginx
    ports:
      - 5000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

  redis:
    image: redis:rc-alpine
    container_name: sa_redis
    ports:
        - 6379:6379
    networks:
      - redis_nt

networks:
  nginx_network:
    driver: bridge
  redis_nt:
    driver: bridge

