version: "3"

services:
  web:
    image: titedios/sa_web:0.1
    container_name: sa_web
    networks:
      - nginx_network
      - redis_nt
    command:
      - /usr/src/app/entrypoint.sh

  model:
    image: titedios/sa_model:0.1
    container_name: sa_model
    networks:
      - redis_nt

  nginx:
    image: nginx:stable-alpine
    container_name: sa_nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - web
    networks:
      - nginx_network

  redis:
    image: redis:rc-alpine
    container_name: sa_redis
    ports:
        - 6379:6379
    networks:
      - redis_nt

networks:
  nginx_network:
    driver: bridge
  redis_nt:
    driver: bridge

